In [22]:
import numpy as np
import pandas as pd
id(np.tile)

4491707456

In [39]:
def getNumpyMatrixCheckerBord(n):
    result = np.zeros((n, n), dtype=int)
    result[::2, 1::2] = 1
    result[1::2, ::2] = 1
    print(result)

getNumpyMatrixCheckerBord(4)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [44]:
a = [10,11,12,13],[15,12,13,14]
np.shape(a)



(2, 4)

In [49]:
np.arange(24).reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
array_1 = np.arange(10)
print(array_1)
print(array_1[[2,5,6]])

[0 1 2 3 4 5 6 7 8 9]
[2 5 6]


In [60]:
array_2 = [1, 2, 3, 5, 4, 6, 7, 8, 5, 3, 2]
print(array_2[0::2])

[1, 3, 4, 7, 5, 2]


In [75]:
arr = np.array([[5,6,7],[7,6,5],[0,8,7]])
print(arr[0,1])

6


In [84]:
list1 = [i for i in range(1000000)]
list2 = [j**2 for j in range(1000000)]
print(len(list1))
import time

t0 = time.time()
multiList = list(map(lambda x,y : x*y, list1, list2 ))
t1 = time.time()
tTaken = t1-t0
print(tTaken)

arr_1 = np.array(list1)
arr_2 = np.array(list2)

t0 = time.time()

npMultiArr = arr_1*arr_2

t1 = time.time()
npTimeTaken = t1-t0
print(npTimeTaken)


print("the ratio of time taken {}".format(tTaken/npTimeTaken))







1000000
0.21515798568725586
0.00871896743774414
the ratio of time taken 24.677003007929997


In [89]:
s = "I love Python programming"
print(s[7:13])
print(s[-18:-12])
print(len("python"))

print(6**7)

Python
Python
6
279936


In [93]:
num = "123456789"
print(num[1::2]) # even number print
print(num[0::2]) # odd number print
print(num[0::4]) # odd number print


2468
13579
159


In [1]:
word = ['1','2','3','4']
word[ : ] = [ ] 
print(word)

[]


In [2]:
if (10 < 0) and (0 < -10):
    print("A")
elif (10 > 0) or False:
    print("B")
else:
    print("C")

B


In [3]:
if True or True:
    if False and True or False:
        print('A')
    elif False and False or True and True:
        print('B')
    else:
        print('C')
else:
    print('D')

B


In [4]:
d = {0: 'Fish', 1: 'Bird', 2: 'Mammal'}
for i in d:
    print(i)

0
1
2


In [6]:
d = {0, 1, 2}
for x in d:
    print(d.add(x))
    
print(d)

None
None
None
{0, 1, 2}


In [22]:
for i in range(1,4):
    print(i*i)
print([i+j for i in "abc" for j in "def"])
"a"*3


1
4
9
['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']


'aaa'

In [41]:
multi = lambda *b : [i*i for i in list(b)]
print(multi(1,2,3,4,4,4,4,4))

[1, 4, 9, 16, 16, 16, 16, 16]


In [216]:
greater = lambda x,y: x if x>y else y

print(greater(4,5))

# Reverse the number
def reverseDigit(n):
    rev = 0
    if (n < 0):
        return rev
    while(n>0):
        rev = (rev*10)+(n%10)
        n = n // 10
                  
                  
    return rev


print(reverseDigit(17))



# n = 17; 
# rev = 0
  
# while(n > 0):
#     print(n) 
#     a = n % 10
#     rev = rev * 10 + a 
#     n = n // 10
      
# print(rev)

5
71


In [195]:
def say(message, times = 1):
    print(message * times)

say('Hello')
say('World', 5)


rev_num = 0
base_pos = 1
  
# Recursive function to reverse 
# digits of num 
def reversDigits(num): 
    global rev_num 
    global base_pos 
    if(num > 0): 
        reversDigits((int)(num / 10)) 
        rev_num += (num % 10) * base_pos 
        base_pos *= 10
    return rev_num 
      
# Driver Code  
num = 4562
print("Reverse of no. is ", 
         reversDigits(num)) 

Hello
WorldWorldWorldWorldWorld
Reverse of no. is  2654


In [47]:
min = (lambda x, y: x if x < y else y)
min(101*99, 102*98)

9996

In [68]:
input_list = ['San Jose', 'San Francisco', 'Santa Fe', 'Houston']
count = sum(list(map(lambda w: 1 if "S" == w[0] else 0 ,input_list)))
print(count)


3


In [70]:
id(count)

4544058560

In [8]:
a = np.arange(0,20)
a_list = [x/(x+1) for x in a]
print(a_list)

[0.0, 0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


In [11]:
f = np.vectorize(lambda x: x/(x+1))
f(a)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ,
       0.90909091, 0.91666667, 0.92307692, 0.92857143, 0.93333333,
       0.9375    , 0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [19]:
import numpy as np
array_1 = np.array([[1,2,3],[2,3,4],[4,2,6]])
eigen = np.linalg.eig(array_1) #Type your answer here
inv = np.linalg.inv(array_1) #Type your answer here
det = np.linalg.det(array_1) #Type your answer here
# print(eigen)
print(inv)
# print(det)


[[-1.66666667  1.          0.16666667]
 [-0.66666667  1.         -0.33333333]
 [ 1.33333333 -1.          0.16666667]]


In [27]:
list1 = np.arange(1,4+1)
series = pd.Series(list1, index = range(1, 4+1))
series.apply(lambda x: x**2)

1     1
2     4
3     9
4    16
dtype: int64

In [28]:
import numpy as np 
import pandas as pd

# Defining the three dataframes indicating the gold, silver, and bronze medal counts
# of different countries
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )

gold.set_index('Country', inplace = True)
silver.set_index('Country', inplace = True)
bronze.set_index('Country', inplace = True)
tot = gold.add(silver, fill_value = 0).add(bronze, fill_value = 0)
print(tot)
total = tot.sort_values(by="Medals", ascending=False)
print(total)

         Medals
Country        
France     53.0
Germany    20.0
Russia     25.0
UK         27.0
USA        72.0
         Medals
Country        
USA        72.0
France     53.0
UK         27.0
Russia     25.0
Germany    20.0


In [87]:
from functools import reduce
def calc_fact(n):
    if (n < 1 or n == 1):
        return 1;
    else:
        return reduce(lambda x, y: x*y, range(1, n+1))
    

print(calc_fact(3));

6


In [116]:
c = [2, 5, 9, 12, 13, 15, 16, 17, 18, 19]
f = [2, 4, 5, 6, 7, 9, 13, 16, 20]
h = [1, 2, 5, 9, 10, 11, 12, 13, 15, 20]

# print(sorted(playNoH))

    

alls = list(filter(lambda x: x in f and x in h, c))
notHokey = list(filter(lambda x: x in f and x not in h, c))
playNone = list(filter(lambda i: (i in c and i in f and i not in h) or (i in f and i in h and i not in c) or (i in c and i in h and i not in f), range(1,21)))
palyTwo = list(filter(lambda i: i not in c and i not in f and i not in h, range(1,21)))
# all_sports = [i for i in c if i in f and i in h]
# cricket_and_football = [i for i in c if i in f and i not in h]
# do_not_play_any = [i for i in range(1, 21) if (i in c and i in f and i not in h) or (i in f and i in h and i not in c) or (i in c and i in h and i not in f)]
# two_sports = [i for i in range(1, 21) if i not in c and i not in f and i not in h]

print(alls)
print(notHokey)
print(playNone)
print(palyTwo)
# print(sorted(all_sports))
# print(sorted(cricket_and_football))
# print(sorted(do_not_play_any))
# print(sorted(two_sports))


[2, 5, 9, 13]
[16]
[12, 15, 16, 20]
[3, 8, 14]


In [183]:
comptetitor = ["newshop", "fashion"]
list1 = ["newshop good", "newshop good", "NewShop good", "fashion is good"]
list1 = [x.lower() for x in list1]
d1 = {}
for com in comptetitor:
    for l in list1:
        if (com.lower() in l):
            if com in d1:
                d1[com] = d1[com] + 1
            else:
                d1[com] = 1

d2 = sorted(d1.items() ,  key=lambda x: x[1], reverse=True)
d3 = []
for elem in range(1):
#     print(elem[0] , " ::" , elem[1])
    d3.append(d2[elem][0])

print(d3)

['newshop']


In [231]:
list2 = {}
for i in [2, 2, 7, 7, 1, 1, 3, 9, 9]:
    list2[i] = 1
print(list2)

{2: 1, 7: 1, 1: 1, 3: 1, 9: 1}


In [236]:
n = 5
for i in range(1, n+1):
    for j in range(n-i):
        print(" ", end="")
    for k in range(i-1):
        print("*_", end="")
    print("*")

    *
   *_*
  *_*_*
 *_*_*_*
*_*_*_*_*


In [237]:
n = 5
m = 2*n -1
asciichar = 96+n
i = 0
while i < n:
    j = 0
    while j < m :
        if( (m//2)-i <= j <= (m//2)  +i):
            print(chr(asciichar),end = "")
        else:
            print("-",end = "")
        
        j+=1
    print(" ")
    i+=1
    
i = 1
while i < n:
    j = 0
    while j < m :
        if( i <= j <= m-1 -i):
            print(chr(asciichar),end = "")
        else:
            print("-",end = "")
        
        j+=1
        
    print(" ")
    i+=1

----e---- 
---eee--- 
--eeeee-- 
-eeeeeee- 
eeeeeeeee 
-eeeeeee- 
--eeeee-- 
---eee--- 
----e---- 


In [240]:
startcharoriginal = chr(96+n)
startchar = startcharoriginal
for i in range(0,n):
    print("-"*(n-i-1)*2,end = '')
    for j in range(0,i+1):
        print(startchar,end = '')
        if j<i:
            print("-",end = '')
        curr = 96+n-j-1
        startchar = chr(curr)
    for k in range(1,i+1):
        startchar = chr(curr+k+1)
        print("-",end = '')
        print(startchar,end = '')
    startchar = startcharoriginal
    print("-"*(n-i-1)*2)
for i in range(n-2,-1,-1):
    print("-"*(n-i-1)*2,end = '')
    for j in range(0,i+1):
        print(startchar,end = '')
        if j<i:
            print("-",end = '')
        curr = 96+n-j-1
        startchar = chr(curr)
    for k in range(1,i+1):
        startchar = chr(curr+k+1)
        print("-",end = '')
        print(startchar,end = '')
    startchar = startcharoriginal
    print("-"*(n-i-1)*2)  
    

--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


In [262]:
L=[10,20,30,40,50,60,70,80,90,100]
# print(L.index(2))
print(L[1:-1:2])
print([L[i] for i in range(1,9,2)])

L.extend([1,2])
print(L)

[20, 40, 60, 80]
[20, 40, 60, 80]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 1, 2]


In [268]:
import autopy
autopy.mouse.move(200,300)