In [1]:
import numpy as np

In [2]:
A = np.array([[1,2], [2,3]])

B = np.array([[4,5], [6,9]])

In [3]:
A

array([[1, 2],
       [2, 3]])

In [4]:
B

array([[4, 5],
       [6, 9]])

In [5]:
C = A @ B

In [6]:
C

array([[16, 23],
       [26, 37]])

# Matrix Inverse

In [7]:
M = np.array([[2,-1], [1,1]])

In [10]:
M

array([[ 2, -1],
       [ 1,  1]])

In [11]:
Inv = np.linalg.inv(M)

In [12]:
Inv

array([[ 0.33333333,  0.33333333],
       [-0.33333333,  0.66666667]])

In [13]:
X = np.linalg.inv(Inv)

In [14]:
X

array([[ 2., -1.],
       [ 1.,  1.]])

In [15]:
M1 = np.array([[2,1,1], [3, 2,1], [2,1,2]])

In [16]:
M1

array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [17]:
inv1 = np.linalg.inv(M1)

In [18]:
inv1

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [19]:
v1 = np.array([[8],[6]])

In [20]:
B2 = np.array([[2,-2],[1,1]])
B2

array([[ 2, -2],
       [ 1,  1]])

In [21]:
M = np.linalg.inv(B2)

In [22]:
M

array([[ 0.25,  0.5 ],
       [-0.25,  0.5 ]])

In [24]:
M @ B2

array([[1., 0.],
       [0., 1.]])

In [25]:
M @ v1

array([[5.],
       [1.]])

In [26]:
v1 = np.array([[5],[1]])

In [27]:
B2 = np.array([[2,-2],[1,1]])
B2

array([[ 2, -2],
       [ 1,  1]])

In [28]:
M = B2

In [29]:
M @ v1

array([[8],
       [6]])

In [30]:
v1 = np.array([[25], [28]])

In [31]:
B2 = np.array([[1, 1], [-2, 1]])

In [32]:
M = np.linalg.inv(B2)

In [33]:
M

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [37]:
M @ np.array([[9], [18]])

array([[-3.],
       [12.]])

In [38]:
v1 = np.array([[1], [1]])

In [39]:
B1 = np.array([[1, 2], [1, 1]])

In [40]:
M = B1

In [41]:
M

array([[1, 2],
       [1, 1]])

In [42]:
M@v1

array([[3],
       [2]])

In [45]:
v1 = np.array([[3], [2]])

In [46]:
v1

array([[3],
       [2]])

In [43]:
M = np.linalg.inv(np.array([[3, -3], [4, -5]]))

In [48]:
M

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [47]:
M @v1

array([[3.],
       [2.]])