In [1]:
import numpy as np

In [2]:
A = np.array([[1,2], [2,3]])

B = np.array([[4,5], [6,9]])

In [3]:
A

array([[1, 2],
       [2, 3]])

In [4]:
B

array([[4, 5],
       [6, 9]])

In [5]:
C = A @ B

In [6]:
C

array([[16, 23],
       [26, 37]])

# Matrix Inverse

In [7]:
M = np.array([[2,-1], [1,1]])

In [10]:
M

array([[ 2, -1],
       [ 1,  1]])

In [11]:
Inv = np.linalg.inv(M)

In [12]:
Inv

array([[ 0.33333333,  0.33333333],
       [-0.33333333,  0.66666667]])

In [13]:
X = np.linalg.inv(Inv)

In [14]:
X

array([[ 2., -1.],
       [ 1.,  1.]])

In [15]:
M1 = np.array([[2,1,1], [3, 2,1], [2,1,2]])

In [16]:
M1

array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [17]:
inv1 = np.linalg.inv(M1)

In [18]:
inv1

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])